//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeykentHastaRandevuSistemiData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BHRSEntities : DbContext
    {
        public BHRSEntities()
            : base("name=BHRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doktor> Doktor { get; set; }
        public virtual DbSet<DoktorPoliklinik> DoktorPoliklinik { get; set; }
        public virtual DbSet<Hasta> Hasta { get; set; }
        public virtual DbSet<HastaRandevu> HastaRandevu { get; set; }
        public virtual DbSet<KullaniciBilgileri> KullaniciBilgileri { get; set; }
        public virtual DbSet<Poliklinik> Poliklinik { get; set; }
    }
}
