//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeykentHastaRandevuSistemiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoktorPoliklinik
    {
        public int RecId { get; set; }
        public int PoliklinikId { get; set; }
        public int DoktorId { get; set; }
        public int StatusTypeId { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Poliklinik Poliklinik { get; set; }
    }
}
