//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeykentHastaRandevuSistemiData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KullaniciBilgileri()
        {
            this.Doktor = new HashSet<Doktor>();
            this.Hasta = new HashSet<Hasta>();
        }
    
        public int RecId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string KimlikNumarasi { get; set; }
        public int Cinsiyet { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public string CepNumarasi { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doktor> Doktor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hasta> Hasta { get; set; }
    }
}
